
spring:
  profiles:
    active: '@appPropProfile@'

logging:
  level:
    root: INFO

server:
  port: 8080

springdoc.swagger-ui.path: /


data-sources:
  - name: data-base-1
    strategy: postgres
    url: jdbc:postgresql://localhost:5433/db1
    user: user1
    password: password1
    table: users
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name

  - name: data-base-2
    strategy: postgres
    url: jdbc:postgresql://localhost:5434/db2
    user: user2
    password: password2
    table: user_table
    mapping:
      id: ldap_id
      username: ldap_login
      name: name
      surname: surname

  - name: data-base-3
    strategy: mysql
    url: jdbc:mysql://localhost:3306/exampledb
    user: exampleuser
    password: examplepassword
    table: users
    mapping:
      id: id
      username: username
      name: name
      surname: surname