
spring:
  profiles:
    active: '@appPropProfile@'

logging:
  level:
    root: INFO

server:
  port: 8080

springdoc.swagger-ui.path: /


data-sources:
  - name: data-base-1
    strategy: postgres
    url: jdbc:postgresql://localhost:5433/pg_db
    user: user
    password: pass
    table: p_users
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name

  - name: data-base-2
    strategy: mysql
    url: jdbc:mysql://localhost:3306/mysql_db
    user: mysql_user
    password: mysql_pass
    table: m_users
    mapping:
      id: id
      username: uname
      name: name
      surname: sname